FROM python:3.11-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential libpq-dev gcc \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install gunicorn

COPY wsgi.py ./wsgi.py
COPY application/controllers ./application/controllers
COPY application/models.py ./application/models.py
COPY application/__init__.py ./application/__init__.py
COPY application/services ./application/services
COPY application/schemas ./application/schemas
COPY  ./application/celery_app.py ./application/celery_app.py


RUN useradd -ms /bin/bash appuser && chown -R appuser:appuser /app
USER appuser

ENV FLASK_APP=wsgi.py
ENV PYTHONUNBUFFERED=1

EXPOSE 8000

CMD ["gunicorn", "--workers", "3", "--bind", "0.0.0.0:8000", "wsgi:app"]
