# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: classification.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'classification.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x63lassification.proto\x12\x0e\x63lassification\"\x83\x01\n\x0f\x43lassifyRequest\x12?\n\x08\x66\x65\x61tures\x18\x01 \x03(\x0b\x32-.classification.ClassifyRequest.FeaturesEntry\x1a/\n\rFeaturesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\"\xb0\x01\n\x10\x43lassifyResponse\x12\x15\n\ranomaly_class\x18\x01 \x01(\x05\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12@\n\x08metadata\x18\x03 \x03(\x0b\x32..classification.ClassifyResponse.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32m\n\x1c\x41nomalyClassificationService\x12M\n\x08\x43lassify\x12\x1f.classification.ClassifyRequest\x1a .classification.ClassifyResponseB\x03\x90\x01\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'classification_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\220\001\000'
  _globals['_CLASSIFYREQUEST_FEATURESENTRY']._loaded_options = None
  _globals['_CLASSIFYREQUEST_FEATURESENTRY']._serialized_options = b'8\001'
  _globals['_CLASSIFYRESPONSE_METADATAENTRY']._loaded_options = None
  _globals['_CLASSIFYRESPONSE_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_CLASSIFYREQUEST']._serialized_start=41
  _globals['_CLASSIFYREQUEST']._serialized_end=172
  _globals['_CLASSIFYREQUEST_FEATURESENTRY']._serialized_start=125
  _globals['_CLASSIFYREQUEST_FEATURESENTRY']._serialized_end=172
  _globals['_CLASSIFYRESPONSE']._serialized_start=175
  _globals['_CLASSIFYRESPONSE']._serialized_end=351
  _globals['_CLASSIFYRESPONSE_METADATAENTRY']._serialized_start=304
  _globals['_CLASSIFYRESPONSE_METADATAENTRY']._serialized_end=351
  _globals['_ANOMALYCLASSIFICATIONSERVICE']._serialized_start=353
  _globals['_ANOMALYCLASSIFICATIONSERVICE']._serialized_end=462
# @@protoc_insertion_point(module_scope)
