# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ml-service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ml-service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10ml-service.proto\x12\nml_service\"\"\n\x0ePredictRequest\x12\x10\n\x08\x66\x65\x61tures\x18\x01 \x03(\x02\"%\n\x0fPredictResponse\x12\x12\n\nprediction\x18\x01 \x01(\x05\x32O\n\tMLService\x12\x42\n\x07Predict\x12\x1a.ml_service.PredictRequest\x1a\x1b.ml_service.PredictResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ml_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREDICTREQUEST']._serialized_start=32
  _globals['_PREDICTREQUEST']._serialized_end=66
  _globals['_PREDICTRESPONSE']._serialized_start=68
  _globals['_PREDICTRESPONSE']._serialized_end=105
  _globals['_MLSERVICE']._serialized_start=107
  _globals['_MLSERVICE']._serialized_end=186
# @@protoc_insertion_point(module_scope)
